// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: publicrpc/v1/publicrpc.proto

package publicrpcv1

import (
	v1 "github.com/certusone/wormhole/node/pkg/proto/gossip/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainID int32

const (
	ChainID_CHAIN_ID_UNSPECIFIED ChainID = 0
	ChainID_CHAIN_ID_SOLANA      ChainID = 1
	ChainID_CHAIN_ID_ETHEREUM    ChainID = 2
	ChainID_CHAIN_ID_TERRA       ChainID = 3 // WARNING: CHAIN_ID_TERRA is only supported in devnet / Tilt.
	ChainID_CHAIN_ID_BSC         ChainID = 4
	ChainID_CHAIN_ID_POLYGON     ChainID = 5
	ChainID_CHAIN_ID_AVALANCHE   ChainID = 6
	// OBSOLETE: CHAIN_ID_OASIS = 7;
	ChainID_CHAIN_ID_ALGORAND ChainID = 8
	// OBSOLETE: CHAIN_ID_AURORA = 9;
	ChainID_CHAIN_ID_FANTOM ChainID = 10
	// OBSOLETE: CHAIN_ID_KARURA = 11;
	// OBSOLETE: CHAIN_ID_ACALA = 12;
	ChainID_CHAIN_ID_KLAYTN   ChainID = 13
	ChainID_CHAIN_ID_CELO     ChainID = 14
	ChainID_CHAIN_ID_NEAR     ChainID = 15
	ChainID_CHAIN_ID_MOONBEAM ChainID = 16
	// OBSOLETE: CHAIN_ID_NEON = 17;
	ChainID_CHAIN_ID_TERRA2    ChainID = 18 // WARNING: CHAIN_ID_TERRA2 is only supported in devnet / Tilt.
	ChainID_CHAIN_ID_INJECTIVE ChainID = 19
	ChainID_CHAIN_ID_OSMOSIS   ChainID = 20
	ChainID_CHAIN_ID_SUI       ChainID = 21
	ChainID_CHAIN_ID_APTOS     ChainID = 22
	ChainID_CHAIN_ID_ARBITRUM  ChainID = 23
	ChainID_CHAIN_ID_OPTIMISM  ChainID = 24
	ChainID_CHAIN_ID_GNOSIS    ChainID = 25
	ChainID_CHAIN_ID_PYTHNET   ChainID = 26
	// 27 belongs to a chain that was never deployed.
	// OBSOLETE: CHAIN_ID_XPLA = 28;
	ChainID_CHAIN_ID_BTC       ChainID = 29
	ChainID_CHAIN_ID_BASE      ChainID = 30
	ChainID_CHAIN_ID_FILECOIN  ChainID = 31
	ChainID_CHAIN_ID_SEI       ChainID = 32
	ChainID_CHAIN_ID_ROOTSTOCK ChainID = 33
	ChainID_CHAIN_ID_SCROLL    ChainID = 34
	ChainID_CHAIN_ID_MANTLE    ChainID = 35
	// OBSOLETE: CHAIN_ID_BLAST = 36;
	ChainID_CHAIN_ID_XLAYER    ChainID = 37
	ChainID_CHAIN_ID_LINEA     ChainID = 38
	ChainID_CHAIN_ID_BERACHAIN ChainID = 39
	ChainID_CHAIN_ID_SEIEVM    ChainID = 40
	ChainID_CHAIN_ID_ECLIPSE   ChainID = 41
	ChainID_CHAIN_ID_BOB       ChainID = 42
	// OBSOLETE: CHAIN_ID_SNAXCHAIN = 43;
	ChainID_CHAIN_ID_UNICHAIN         ChainID = 44
	ChainID_CHAIN_ID_WORLDCHAIN       ChainID = 45
	ChainID_CHAIN_ID_INK              ChainID = 46
	ChainID_CHAIN_ID_HYPER_EVM        ChainID = 47
	ChainID_CHAIN_ID_MONAD            ChainID = 48
	ChainID_CHAIN_ID_MOVEMENT         ChainID = 49
	ChainID_CHAIN_ID_MEZO             ChainID = 50
	ChainID_CHAIN_ID_FOGO             ChainID = 51
	ChainID_CHAIN_ID_SONIC            ChainID = 52
	ChainID_CHAIN_ID_CONVERGE         ChainID = 53
	ChainID_CHAIN_ID_CODEX            ChainID = 54
	ChainID_CHAIN_ID_PLUME            ChainID = 55
	ChainID_CHAIN_ID_AZTEC            ChainID = 56
	ChainID_CHAIN_ID_XRPLEVM          ChainID = 57
	ChainID_CHAIN_ID_PLASMA           ChainID = 58
	ChainID_CHAIN_ID_CREDITCOIN       ChainID = 59
	ChainID_CHAIN_ID_STACKS           ChainID = 60
	ChainID_CHAIN_ID_TON              ChainID = 61
	ChainID_CHAIN_ID_WORMCHAIN        ChainID = 3104
	ChainID_CHAIN_ID_COSMOSHUB        ChainID = 4000
	ChainID_CHAIN_ID_EVMOS            ChainID = 4001
	ChainID_CHAIN_ID_KUJIRA           ChainID = 4002
	ChainID_CHAIN_ID_NEUTRON          ChainID = 4003
	ChainID_CHAIN_ID_CELESTIA         ChainID = 4004
	ChainID_CHAIN_ID_STARGAZE         ChainID = 4005
	ChainID_CHAIN_ID_SEDA             ChainID = 4006
	ChainID_CHAIN_ID_DYMENSION        ChainID = 4007
	ChainID_CHAIN_ID_PROVENANCE       ChainID = 4008
	ChainID_CHAIN_ID_NOBLE            ChainID = 4009
	ChainID_CHAIN_ID_SEPOLIA          ChainID = 10002
	ChainID_CHAIN_ID_ARBITRUM_SEPOLIA ChainID = 10003
	ChainID_CHAIN_ID_BASE_SEPOLIA     ChainID = 10004
	ChainID_CHAIN_ID_OPTIMISM_SEPOLIA ChainID = 10005
	ChainID_CHAIN_ID_HOLESKY          ChainID = 10006
	ChainID_CHAIN_ID_POLYGON_SEPOLIA  ChainID = 10007 // OBSOLETE: CHAIN_ID_MONAD_DEVNET = 10008;
)

// Enum value maps for ChainID.
var (
	ChainID_name = map[int32]string{
		0:     "CHAIN_ID_UNSPECIFIED",
		1:     "CHAIN_ID_SOLANA",
		2:     "CHAIN_ID_ETHEREUM",
		3:     "CHAIN_ID_TERRA",
		4:     "CHAIN_ID_BSC",
		5:     "CHAIN_ID_POLYGON",
		6:     "CHAIN_ID_AVALANCHE",
		8:     "CHAIN_ID_ALGORAND",
		10:    "CHAIN_ID_FANTOM",
		13:    "CHAIN_ID_KLAYTN",
		14:    "CHAIN_ID_CELO",
		15:    "CHAIN_ID_NEAR",
		16:    "CHAIN_ID_MOONBEAM",
		18:    "CHAIN_ID_TERRA2",
		19:    "CHAIN_ID_INJECTIVE",
		20:    "CHAIN_ID_OSMOSIS",
		21:    "CHAIN_ID_SUI",
		22:    "CHAIN_ID_APTOS",
		23:    "CHAIN_ID_ARBITRUM",
		24:    "CHAIN_ID_OPTIMISM",
		25:    "CHAIN_ID_GNOSIS",
		26:    "CHAIN_ID_PYTHNET",
		29:    "CHAIN_ID_BTC",
		30:    "CHAIN_ID_BASE",
		31:    "CHAIN_ID_FILECOIN",
		32:    "CHAIN_ID_SEI",
		33:    "CHAIN_ID_ROOTSTOCK",
		34:    "CHAIN_ID_SCROLL",
		35:    "CHAIN_ID_MANTLE",
		37:    "CHAIN_ID_XLAYER",
		38:    "CHAIN_ID_LINEA",
		39:    "CHAIN_ID_BERACHAIN",
		40:    "CHAIN_ID_SEIEVM",
		41:    "CHAIN_ID_ECLIPSE",
		42:    "CHAIN_ID_BOB",
		44:    "CHAIN_ID_UNICHAIN",
		45:    "CHAIN_ID_WORLDCHAIN",
		46:    "CHAIN_ID_INK",
		47:    "CHAIN_ID_HYPER_EVM",
		48:    "CHAIN_ID_MONAD",
		49:    "CHAIN_ID_MOVEMENT",
		50:    "CHAIN_ID_MEZO",
		51:    "CHAIN_ID_FOGO",
		52:    "CHAIN_ID_SONIC",
		53:    "CHAIN_ID_CONVERGE",
		54:    "CHAIN_ID_CODEX",
		55:    "CHAIN_ID_PLUME",
		56:    "CHAIN_ID_AZTEC",
		57:    "CHAIN_ID_XRPLEVM",
		58:    "CHAIN_ID_PLASMA",
		59:    "CHAIN_ID_CREDITCOIN",
		60:    "CHAIN_ID_STACKS",
		61:    "CHAIN_ID_TON",
		3104:  "CHAIN_ID_WORMCHAIN",
		4000:  "CHAIN_ID_COSMOSHUB",
		4001:  "CHAIN_ID_EVMOS",
		4002:  "CHAIN_ID_KUJIRA",
		4003:  "CHAIN_ID_NEUTRON",
		4004:  "CHAIN_ID_CELESTIA",
		4005:  "CHAIN_ID_STARGAZE",
		4006:  "CHAIN_ID_SEDA",
		4007:  "CHAIN_ID_DYMENSION",
		4008:  "CHAIN_ID_PROVENANCE",
		4009:  "CHAIN_ID_NOBLE",
		10002: "CHAIN_ID_SEPOLIA",
		10003: "CHAIN_ID_ARBITRUM_SEPOLIA",
		10004: "CHAIN_ID_BASE_SEPOLIA",
		10005: "CHAIN_ID_OPTIMISM_SEPOLIA",
		10006: "CHAIN_ID_HOLESKY",
		10007: "CHAIN_ID_POLYGON_SEPOLIA",
	}
	ChainID_value = map[string]int32{
		"CHAIN_ID_UNSPECIFIED":      0,
		"CHAIN_ID_SOLANA":           1,
		"CHAIN_ID_ETHEREUM":         2,
		"CHAIN_ID_TERRA":            3,
		"CHAIN_ID_BSC":              4,
		"CHAIN_ID_POLYGON":          5,
		"CHAIN_ID_AVALANCHE":        6,
		"CHAIN_ID_ALGORAND":         8,
		"CHAIN_ID_FANTOM":           10,
		"CHAIN_ID_KLAYTN":           13,
		"CHAIN_ID_CELO":             14,
		"CHAIN_ID_NEAR":             15,
		"CHAIN_ID_MOONBEAM":         16,
		"CHAIN_ID_TERRA2":           18,
		"CHAIN_ID_INJECTIVE":        19,
		"CHAIN_ID_OSMOSIS":          20,
		"CHAIN_ID_SUI":              21,
		"CHAIN_ID_APTOS":            22,
		"CHAIN_ID_ARBITRUM":         23,
		"CHAIN_ID_OPTIMISM":         24,
		"CHAIN_ID_GNOSIS":           25,
		"CHAIN_ID_PYTHNET":          26,
		"CHAIN_ID_BTC":              29,
		"CHAIN_ID_BASE":             30,
		"CHAIN_ID_FILECOIN":         31,
		"CHAIN_ID_SEI":              32,
		"CHAIN_ID_ROOTSTOCK":        33,
		"CHAIN_ID_SCROLL":           34,
		"CHAIN_ID_MANTLE":           35,
		"CHAIN_ID_XLAYER":           37,
		"CHAIN_ID_LINEA":            38,
		"CHAIN_ID_BERACHAIN":        39,
		"CHAIN_ID_SEIEVM":           40,
		"CHAIN_ID_ECLIPSE":          41,
		"CHAIN_ID_BOB":              42,
		"CHAIN_ID_UNICHAIN":         44,
		"CHAIN_ID_WORLDCHAIN":       45,
		"CHAIN_ID_INK":              46,
		"CHAIN_ID_HYPER_EVM":        47,
		"CHAIN_ID_MONAD":            48,
		"CHAIN_ID_MOVEMENT":         49,
		"CHAIN_ID_MEZO":             50,
		"CHAIN_ID_FOGO":             51,
		"CHAIN_ID_SONIC":            52,
		"CHAIN_ID_CONVERGE":         53,
		"CHAIN_ID_CODEX":            54,
		"CHAIN_ID_PLUME":            55,
		"CHAIN_ID_AZTEC":            56,
		"CHAIN_ID_XRPLEVM":          57,
		"CHAIN_ID_PLASMA":           58,
		"CHAIN_ID_CREDITCOIN":       59,
		"CHAIN_ID_STACKS":           60,
		"CHAIN_ID_TON":              61,
		"CHAIN_ID_WORMCHAIN":        3104,
		"CHAIN_ID_COSMOSHUB":        4000,
		"CHAIN_ID_EVMOS":            4001,
		"CHAIN_ID_KUJIRA":           4002,
		"CHAIN_ID_NEUTRON":          4003,
		"CHAIN_ID_CELESTIA":         4004,
		"CHAIN_ID_STARGAZE":         4005,
		"CHAIN_ID_SEDA":             4006,
		"CHAIN_ID_DYMENSION":        4007,
		"CHAIN_ID_PROVENANCE":       4008,
		"CHAIN_ID_NOBLE":            4009,
		"CHAIN_ID_SEPOLIA":          10002,
		"CHAIN_ID_ARBITRUM_SEPOLIA": 10003,
		"CHAIN_ID_BASE_SEPOLIA":     10004,
		"CHAIN_ID_OPTIMISM_SEPOLIA": 10005,
		"CHAIN_ID_HOLESKY":          10006,
		"CHAIN_ID_POLYGON_SEPOLIA":  10007,
	}
)

func (x ChainID) Enum() *ChainID {
	p := new(ChainID)
	*p = x
	return p
}

func (x ChainID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainID) Descriptor() protoreflect.EnumDescriptor {
	return file_publicrpc_v1_publicrpc_proto_enumTypes[0].Descriptor()
}

func (ChainID) Type() protoreflect.EnumType {
	return &file_publicrpc_v1_publicrpc_proto_enumTypes[0]
}

func (x ChainID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainID.Descriptor instead.
func (ChainID) EnumDescriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{0}
}

// MessageID is a VAA's globally unique identifier (see data availability design document).
type MessageID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Emitter chain ID.
	EmitterChain ChainID `protobuf:"varint,1,opt,name=emitter_chain,json=emitterChain,proto3,enum=publicrpc.v1.ChainID" json:"emitter_chain,omitempty"`
	// Hex-encoded (without leading 0x) emitter address.
	EmitterAddress string `protobuf:"bytes,2,opt,name=emitter_address,json=emitterAddress,proto3" json:"emitter_address,omitempty"`
	// Sequence number for (emitter_chain, emitter_address).
	Sequence      uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageID) Reset() {
	*x = MessageID{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageID) ProtoMessage() {}

func (x *MessageID) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageID.ProtoReflect.Descriptor instead.
func (*MessageID) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{0}
}

func (x *MessageID) GetEmitterChain() ChainID {
	if x != nil {
		return x.EmitterChain
	}
	return ChainID_CHAIN_ID_UNSPECIFIED
}

func (x *MessageID) GetEmitterAddress() string {
	if x != nil {
		return x.EmitterAddress
	}
	return ""
}

func (x *MessageID) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type GetSignedVAARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     *MessageID             `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignedVAARequest) Reset() {
	*x = GetSignedVAARequest{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignedVAARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignedVAARequest) ProtoMessage() {}

func (x *GetSignedVAARequest) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignedVAARequest.ProtoReflect.Descriptor instead.
func (*GetSignedVAARequest) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetSignedVAARequest) GetMessageId() *MessageID {
	if x != nil {
		return x.MessageId
	}
	return nil
}

type GetSignedVAAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaaBytes      []byte                 `protobuf:"bytes,1,opt,name=vaa_bytes,json=vaaBytes,proto3" json:"vaa_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignedVAAResponse) Reset() {
	*x = GetSignedVAAResponse{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignedVAAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignedVAAResponse) ProtoMessage() {}

func (x *GetSignedVAAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignedVAAResponse.ProtoReflect.Descriptor instead.
func (*GetSignedVAAResponse) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetSignedVAAResponse) GetVaaBytes() []byte {
	if x != nil {
		return x.VaaBytes
	}
	return nil
}

type GetLastHeartbeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastHeartbeatsRequest) Reset() {
	*x = GetLastHeartbeatsRequest{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastHeartbeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastHeartbeatsRequest) ProtoMessage() {}

func (x *GetLastHeartbeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastHeartbeatsRequest.ProtoReflect.Descriptor instead.
func (*GetLastHeartbeatsRequest) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{3}
}

type GetLastHeartbeatsResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Entries       []*GetLastHeartbeatsResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastHeartbeatsResponse) Reset() {
	*x = GetLastHeartbeatsResponse{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastHeartbeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastHeartbeatsResponse) ProtoMessage() {}

func (x *GetLastHeartbeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastHeartbeatsResponse.ProtoReflect.Descriptor instead.
func (*GetLastHeartbeatsResponse) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetLastHeartbeatsResponse) GetEntries() []*GetLastHeartbeatsResponse_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetCurrentGuardianSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentGuardianSetRequest) Reset() {
	*x = GetCurrentGuardianSetRequest{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentGuardianSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentGuardianSetRequest) ProtoMessage() {}

func (x *GetCurrentGuardianSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentGuardianSetRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentGuardianSetRequest) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{5}
}

type GetCurrentGuardianSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuardianSet   *GuardianSet           `protobuf:"bytes,1,opt,name=guardian_set,json=guardianSet,proto3" json:"guardian_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentGuardianSetResponse) Reset() {
	*x = GetCurrentGuardianSetResponse{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentGuardianSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentGuardianSetResponse) ProtoMessage() {}

func (x *GetCurrentGuardianSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentGuardianSetResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentGuardianSetResponse) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{6}
}

func (x *GetCurrentGuardianSetResponse) GetGuardianSet() *GuardianSet {
	if x != nil {
		return x.GuardianSet
	}
	return nil
}

type GuardianSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Guardian set index
	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// List of guardian addresses as human-readable hex-encoded (leading 0x) addresses.
	Addresses     []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardianSet) Reset() {
	*x = GuardianSet{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardianSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardianSet) ProtoMessage() {}

func (x *GuardianSet) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardianSet.ProtoReflect.Descriptor instead.
func (*GuardianSet) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{7}
}

func (x *GuardianSet) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GuardianSet) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type GovernorGetAvailableNotionalByChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GovernorGetAvailableNotionalByChainRequest) Reset() {
	*x = GovernorGetAvailableNotionalByChainRequest{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernorGetAvailableNotionalByChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernorGetAvailableNotionalByChainRequest) ProtoMessage() {}

func (x *GovernorGetAvailableNotionalByChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernorGetAvailableNotionalByChainRequest.ProtoReflect.Descriptor instead.
func (*GovernorGetAvailableNotionalByChainRequest) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{8}
}

type GovernorGetAvailableNotionalByChainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// There is an entry for each chain that is being governed.
	// Chains that are not being governed are not listed, and assumed to be unlimited.
	Entries       []*GovernorGetAvailableNotionalByChainResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GovernorGetAvailableNotionalByChainResponse) Reset() {
	*x = GovernorGetAvailableNotionalByChainResponse{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernorGetAvailableNotionalByChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernorGetAvailableNotionalByChainResponse) ProtoMessage() {}

func (x *GovernorGetAvailableNotionalByChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernorGetAvailableNotionalByChainResponse.ProtoReflect.Descriptor instead.
func (*GovernorGetAvailableNotionalByChainResponse) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{9}
}

func (x *GovernorGetAvailableNotionalByChainResponse) GetEntries() []*GovernorGetAvailableNotionalByChainResponse_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GovernorGetEnqueuedVAAsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GovernorGetEnqueuedVAAsRequest) Reset() {
	*x = GovernorGetEnqueuedVAAsRequest{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernorGetEnqueuedVAAsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernorGetEnqueuedVAAsRequest) ProtoMessage() {}

func (x *GovernorGetEnqueuedVAAsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernorGetEnqueuedVAAsRequest.ProtoReflect.Descriptor instead.
func (*GovernorGetEnqueuedVAAsRequest) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{10}
}

type GovernorGetEnqueuedVAAsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// There is an entry for each enqueued vaa.
	Entries       []*GovernorGetEnqueuedVAAsResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GovernorGetEnqueuedVAAsResponse) Reset() {
	*x = GovernorGetEnqueuedVAAsResponse{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernorGetEnqueuedVAAsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernorGetEnqueuedVAAsResponse) ProtoMessage() {}

func (x *GovernorGetEnqueuedVAAsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernorGetEnqueuedVAAsResponse.ProtoReflect.Descriptor instead.
func (*GovernorGetEnqueuedVAAsResponse) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{11}
}

func (x *GovernorGetEnqueuedVAAsResponse) GetEntries() []*GovernorGetEnqueuedVAAsResponse_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GovernorIsVAAEnqueuedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     *MessageID             `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GovernorIsVAAEnqueuedRequest) Reset() {
	*x = GovernorIsVAAEnqueuedRequest{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernorIsVAAEnqueuedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernorIsVAAEnqueuedRequest) ProtoMessage() {}

func (x *GovernorIsVAAEnqueuedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernorIsVAAEnqueuedRequest.ProtoReflect.Descriptor instead.
func (*GovernorIsVAAEnqueuedRequest) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{12}
}

func (x *GovernorIsVAAEnqueuedRequest) GetMessageId() *MessageID {
	if x != nil {
		return x.MessageId
	}
	return nil
}

type GovernorIsVAAEnqueuedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnqueued    bool                   `protobuf:"varint,1,opt,name=is_enqueued,json=isEnqueued,proto3" json:"is_enqueued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GovernorIsVAAEnqueuedResponse) Reset() {
	*x = GovernorIsVAAEnqueuedResponse{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernorIsVAAEnqueuedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernorIsVAAEnqueuedResponse) ProtoMessage() {}

func (x *GovernorIsVAAEnqueuedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernorIsVAAEnqueuedResponse.ProtoReflect.Descriptor instead.
func (*GovernorIsVAAEnqueuedResponse) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{13}
}

func (x *GovernorIsVAAEnqueuedResponse) GetIsEnqueued() bool {
	if x != nil {
		return x.IsEnqueued
	}
	return false
}

type GovernorGetTokenListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GovernorGetTokenListRequest) Reset() {
	*x = GovernorGetTokenListRequest{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernorGetTokenListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernorGetTokenListRequest) ProtoMessage() {}

func (x *GovernorGetTokenListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernorGetTokenListRequest.ProtoReflect.Descriptor instead.
func (*GovernorGetTokenListRequest) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{14}
}

type GovernorGetTokenListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// There is an entry for each token that applies to the notional TVL calcuation.
	Entries       []*GovernorGetTokenListResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GovernorGetTokenListResponse) Reset() {
	*x = GovernorGetTokenListResponse{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernorGetTokenListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernorGetTokenListResponse) ProtoMessage() {}

func (x *GovernorGetTokenListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernorGetTokenListResponse.ProtoReflect.Descriptor instead.
func (*GovernorGetTokenListResponse) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{15}
}

func (x *GovernorGetTokenListResponse) GetEntries() []*GovernorGetTokenListResponse_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetLastHeartbeatsResponse_Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Verified, hex-encoded (with leading 0x) guardian address. This is the guardian address
	// which signed this heartbeat. The GuardianAddr field inside the heartbeat
	// is NOT verified - remote nodes can put arbitrary data in it.
	VerifiedGuardianAddr string `protobuf:"bytes,1,opt,name=verified_guardian_addr,json=verifiedGuardianAddr,proto3" json:"verified_guardian_addr,omitempty"`
	// Base58-encoded libp2p node address that sent this heartbeat, used to
	// distinguish between multiple nodes running for the same guardian.
	P2PNodeAddr string `protobuf:"bytes,2,opt,name=p2p_node_addr,json=p2pNodeAddr,proto3" json:"p2p_node_addr,omitempty"`
	// Raw heartbeat received from the network. Data is only as trusted
	// as the guardian node that sent it - none of the fields are verified.
	RawHeartbeat  *v1.Heartbeat `protobuf:"bytes,3,opt,name=raw_heartbeat,json=rawHeartbeat,proto3" json:"raw_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastHeartbeatsResponse_Entry) Reset() {
	*x = GetLastHeartbeatsResponse_Entry{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastHeartbeatsResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastHeartbeatsResponse_Entry) ProtoMessage() {}

func (x *GetLastHeartbeatsResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastHeartbeatsResponse_Entry.ProtoReflect.Descriptor instead.
func (*GetLastHeartbeatsResponse_Entry) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetLastHeartbeatsResponse_Entry) GetVerifiedGuardianAddr() string {
	if x != nil {
		return x.VerifiedGuardianAddr
	}
	return ""
}

func (x *GetLastHeartbeatsResponse_Entry) GetP2PNodeAddr() string {
	if x != nil {
		return x.P2PNodeAddr
	}
	return ""
}

func (x *GetLastHeartbeatsResponse_Entry) GetRawHeartbeat() *v1.Heartbeat {
	if x != nil {
		return x.RawHeartbeat
	}
	return nil
}

type GovernorGetAvailableNotionalByChainResponse_Entry struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ChainId                    uint32                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	RemainingAvailableNotional uint64                 `protobuf:"varint,2,opt,name=remaining_available_notional,json=remainingAvailableNotional,proto3" json:"remaining_available_notional,omitempty"`
	NotionalLimit              uint64                 `protobuf:"varint,3,opt,name=notional_limit,json=notionalLimit,proto3" json:"notional_limit,omitempty"`
	BigTransactionSize         uint64                 `protobuf:"varint,4,opt,name=big_transaction_size,json=bigTransactionSize,proto3" json:"big_transaction_size,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GovernorGetAvailableNotionalByChainResponse_Entry) Reset() {
	*x = GovernorGetAvailableNotionalByChainResponse_Entry{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernorGetAvailableNotionalByChainResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernorGetAvailableNotionalByChainResponse_Entry) ProtoMessage() {}

func (x *GovernorGetAvailableNotionalByChainResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernorGetAvailableNotionalByChainResponse_Entry.ProtoReflect.Descriptor instead.
func (*GovernorGetAvailableNotionalByChainResponse_Entry) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GovernorGetAvailableNotionalByChainResponse_Entry) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GovernorGetAvailableNotionalByChainResponse_Entry) GetRemainingAvailableNotional() uint64 {
	if x != nil {
		return x.RemainingAvailableNotional
	}
	return 0
}

func (x *GovernorGetAvailableNotionalByChainResponse_Entry) GetNotionalLimit() uint64 {
	if x != nil {
		return x.NotionalLimit
	}
	return 0
}

func (x *GovernorGetAvailableNotionalByChainResponse_Entry) GetBigTransactionSize() uint64 {
	if x != nil {
		return x.BigTransactionSize
	}
	return 0
}

type GovernorGetEnqueuedVAAsResponse_Entry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EmitterChain   uint32                 `protobuf:"varint,1,opt,name=emitter_chain,json=emitterChain,proto3" json:"emitter_chain,omitempty"`
	EmitterAddress string                 `protobuf:"bytes,2,opt,name=emitter_address,json=emitterAddress,proto3" json:"emitter_address,omitempty"` // human-readable hex-encoded (leading 0x)
	Sequence       uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ReleaseTime    uint32                 `protobuf:"varint,4,opt,name=release_time,json=releaseTime,proto3" json:"release_time,omitempty"`
	NotionalValue  uint64                 `protobuf:"varint,5,opt,name=notional_value,json=notionalValue,proto3" json:"notional_value,omitempty"`
	TxHash         string                 `protobuf:"bytes,6,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GovernorGetEnqueuedVAAsResponse_Entry) Reset() {
	*x = GovernorGetEnqueuedVAAsResponse_Entry{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernorGetEnqueuedVAAsResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernorGetEnqueuedVAAsResponse_Entry) ProtoMessage() {}

func (x *GovernorGetEnqueuedVAAsResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernorGetEnqueuedVAAsResponse_Entry.ProtoReflect.Descriptor instead.
func (*GovernorGetEnqueuedVAAsResponse_Entry) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GovernorGetEnqueuedVAAsResponse_Entry) GetEmitterChain() uint32 {
	if x != nil {
		return x.EmitterChain
	}
	return 0
}

func (x *GovernorGetEnqueuedVAAsResponse_Entry) GetEmitterAddress() string {
	if x != nil {
		return x.EmitterAddress
	}
	return ""
}

func (x *GovernorGetEnqueuedVAAsResponse_Entry) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GovernorGetEnqueuedVAAsResponse_Entry) GetReleaseTime() uint32 {
	if x != nil {
		return x.ReleaseTime
	}
	return 0
}

func (x *GovernorGetEnqueuedVAAsResponse_Entry) GetNotionalValue() uint64 {
	if x != nil {
		return x.NotionalValue
	}
	return 0
}

func (x *GovernorGetEnqueuedVAAsResponse_Entry) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type GovernorGetTokenListResponse_Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginChainId uint32                 `protobuf:"varint,1,opt,name=origin_chain_id,json=originChainId,proto3" json:"origin_chain_id,omitempty"`
	OriginAddress string                 `protobuf:"bytes,2,opt,name=origin_address,json=originAddress,proto3" json:"origin_address,omitempty"` // human-readable hex-encoded (leading 0x)
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GovernorGetTokenListResponse_Entry) Reset() {
	*x = GovernorGetTokenListResponse_Entry{}
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernorGetTokenListResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernorGetTokenListResponse_Entry) ProtoMessage() {}

func (x *GovernorGetTokenListResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_publicrpc_v1_publicrpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernorGetTokenListResponse_Entry.ProtoReflect.Descriptor instead.
func (*GovernorGetTokenListResponse_Entry) Descriptor() ([]byte, []int) {
	return file_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{15, 0}
}

func (x *GovernorGetTokenListResponse_Entry) GetOriginChainId() uint32 {
	if x != nil {
		return x.OriginChainId
	}
	return 0
}

func (x *GovernorGetTokenListResponse_Entry) GetOriginAddress() string {
	if x != nil {
		return x.OriginAddress
	}
	return ""
}

func (x *GovernorGetTokenListResponse_Entry) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_publicrpc_v1_publicrpc_proto protoreflect.FileDescriptor

const file_publicrpc_v1_publicrpc_proto_rawDesc = "" +
	"\n" +
	"\x1cpublicrpc/v1/publicrpc.proto\x12\fpublicrpc.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x16gossip/v1/gossip.proto\"\x8c\x01\n" +
	"\tMessageID\x12:\n" +
	"\remitter_chain\x18\x01 \x01(\x0e2\x15.publicrpc.v1.ChainIDR\femitterChain\x12'\n" +
	"\x0femitter_address\x18\x02 \x01(\tR\x0eemitterAddress\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\"M\n" +
	"\x13GetSignedVAARequest\x126\n" +
	"\n" +
	"message_id\x18\x01 \x01(\v2\x17.publicrpc.v1.MessageIDR\tmessageId\"3\n" +
	"\x14GetSignedVAAResponse\x12\x1b\n" +
	"\tvaa_bytes\x18\x01 \x01(\fR\bvaaBytes\"\x1a\n" +
	"\x18GetLastHeartbeatsRequest\"\x83\x02\n" +
	"\x19GetLastHeartbeatsResponse\x12G\n" +
	"\aentries\x18\x01 \x03(\v2-.publicrpc.v1.GetLastHeartbeatsResponse.EntryR\aentries\x1a\x9c\x01\n" +
	"\x05Entry\x124\n" +
	"\x16verified_guardian_addr\x18\x01 \x01(\tR\x14verifiedGuardianAddr\x12\"\n" +
	"\rp2p_node_addr\x18\x02 \x01(\tR\vp2pNodeAddr\x129\n" +
	"\rraw_heartbeat\x18\x03 \x01(\v2\x14.gossip.v1.HeartbeatR\frawHeartbeat\"\x1e\n" +
	"\x1cGetCurrentGuardianSetRequest\"]\n" +
	"\x1dGetCurrentGuardianSetResponse\x12<\n" +
	"\fguardian_set\x18\x01 \x01(\v2\x19.publicrpc.v1.GuardianSetR\vguardianSet\"A\n" +
	"\vGuardianSet\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\",\n" +
	"*GovernorGetAvailableNotionalByChainRequest\"\xc8\x02\n" +
	"+GovernorGetAvailableNotionalByChainResponse\x12Y\n" +
	"\aentries\x18\x01 \x03(\v2?.publicrpc.v1.GovernorGetAvailableNotionalByChainResponse.EntryR\aentries\x1a\xbd\x01\n" +
	"\x05Entry\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\rR\achainId\x12@\n" +
	"\x1cremaining_available_notional\x18\x02 \x01(\x04R\x1aremainingAvailableNotional\x12%\n" +
	"\x0enotional_limit\x18\x03 \x01(\x04R\rnotionalLimit\x120\n" +
	"\x14big_transaction_size\x18\x04 \x01(\x04R\x12bigTransactionSize\" \n" +
	"\x1eGovernorGetEnqueuedVAAsRequest\"\xc7\x02\n" +
	"\x1fGovernorGetEnqueuedVAAsResponse\x12M\n" +
	"\aentries\x18\x01 \x03(\v23.publicrpc.v1.GovernorGetEnqueuedVAAsResponse.EntryR\aentries\x1a\xd4\x01\n" +
	"\x05Entry\x12#\n" +
	"\remitter_chain\x18\x01 \x01(\rR\femitterChain\x12'\n" +
	"\x0femitter_address\x18\x02 \x01(\tR\x0eemitterAddress\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12!\n" +
	"\frelease_time\x18\x04 \x01(\rR\vreleaseTime\x12%\n" +
	"\x0enotional_value\x18\x05 \x01(\x04R\rnotionalValue\x12\x17\n" +
	"\atx_hash\x18\x06 \x01(\tR\x06txHash\"V\n" +
	"\x1cGovernorIsVAAEnqueuedRequest\x126\n" +
	"\n" +
	"message_id\x18\x01 \x01(\v2\x17.publicrpc.v1.MessageIDR\tmessageId\"@\n" +
	"\x1dGovernorIsVAAEnqueuedResponse\x12\x1f\n" +
	"\vis_enqueued\x18\x01 \x01(\bR\n" +
	"isEnqueued\"\x1d\n" +
	"\x1bGovernorGetTokenListRequest\"\xd8\x01\n" +
	"\x1cGovernorGetTokenListResponse\x12J\n" +
	"\aentries\x18\x01 \x03(\v20.publicrpc.v1.GovernorGetTokenListResponse.EntryR\aentries\x1al\n" +
	"\x05Entry\x12&\n" +
	"\x0forigin_chain_id\x18\x01 \x01(\rR\roriginChainId\x12%\n" +
	"\x0eorigin_address\x18\x02 \x01(\tR\roriginAddress\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price*\x97\f\n" +
	"\aChainID\x12\x18\n" +
	"\x14CHAIN_ID_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCHAIN_ID_SOLANA\x10\x01\x12\x15\n" +
	"\x11CHAIN_ID_ETHEREUM\x10\x02\x12\x12\n" +
	"\x0eCHAIN_ID_TERRA\x10\x03\x12\x10\n" +
	"\fCHAIN_ID_BSC\x10\x04\x12\x14\n" +
	"\x10CHAIN_ID_POLYGON\x10\x05\x12\x16\n" +
	"\x12CHAIN_ID_AVALANCHE\x10\x06\x12\x15\n" +
	"\x11CHAIN_ID_ALGORAND\x10\b\x12\x13\n" +
	"\x0fCHAIN_ID_FANTOM\x10\n" +
	"\x12\x13\n" +
	"\x0fCHAIN_ID_KLAYTN\x10\r\x12\x11\n" +
	"\rCHAIN_ID_CELO\x10\x0e\x12\x11\n" +
	"\rCHAIN_ID_NEAR\x10\x0f\x12\x15\n" +
	"\x11CHAIN_ID_MOONBEAM\x10\x10\x12\x13\n" +
	"\x0fCHAIN_ID_TERRA2\x10\x12\x12\x16\n" +
	"\x12CHAIN_ID_INJECTIVE\x10\x13\x12\x14\n" +
	"\x10CHAIN_ID_OSMOSIS\x10\x14\x12\x10\n" +
	"\fCHAIN_ID_SUI\x10\x15\x12\x12\n" +
	"\x0eCHAIN_ID_APTOS\x10\x16\x12\x15\n" +
	"\x11CHAIN_ID_ARBITRUM\x10\x17\x12\x15\n" +
	"\x11CHAIN_ID_OPTIMISM\x10\x18\x12\x13\n" +
	"\x0fCHAIN_ID_GNOSIS\x10\x19\x12\x14\n" +
	"\x10CHAIN_ID_PYTHNET\x10\x1a\x12\x10\n" +
	"\fCHAIN_ID_BTC\x10\x1d\x12\x11\n" +
	"\rCHAIN_ID_BASE\x10\x1e\x12\x15\n" +
	"\x11CHAIN_ID_FILECOIN\x10\x1f\x12\x10\n" +
	"\fCHAIN_ID_SEI\x10 \x12\x16\n" +
	"\x12CHAIN_ID_ROOTSTOCK\x10!\x12\x13\n" +
	"\x0fCHAIN_ID_SCROLL\x10\"\x12\x13\n" +
	"\x0fCHAIN_ID_MANTLE\x10#\x12\x13\n" +
	"\x0fCHAIN_ID_XLAYER\x10%\x12\x12\n" +
	"\x0eCHAIN_ID_LINEA\x10&\x12\x16\n" +
	"\x12CHAIN_ID_BERACHAIN\x10'\x12\x13\n" +
	"\x0fCHAIN_ID_SEIEVM\x10(\x12\x14\n" +
	"\x10CHAIN_ID_ECLIPSE\x10)\x12\x10\n" +
	"\fCHAIN_ID_BOB\x10*\x12\x15\n" +
	"\x11CHAIN_ID_UNICHAIN\x10,\x12\x17\n" +
	"\x13CHAIN_ID_WORLDCHAIN\x10-\x12\x10\n" +
	"\fCHAIN_ID_INK\x10.\x12\x16\n" +
	"\x12CHAIN_ID_HYPER_EVM\x10/\x12\x12\n" +
	"\x0eCHAIN_ID_MONAD\x100\x12\x15\n" +
	"\x11CHAIN_ID_MOVEMENT\x101\x12\x11\n" +
	"\rCHAIN_ID_MEZO\x102\x12\x11\n" +
	"\rCHAIN_ID_FOGO\x103\x12\x12\n" +
	"\x0eCHAIN_ID_SONIC\x104\x12\x15\n" +
	"\x11CHAIN_ID_CONVERGE\x105\x12\x12\n" +
	"\x0eCHAIN_ID_CODEX\x106\x12\x12\n" +
	"\x0eCHAIN_ID_PLUME\x107\x12\x12\n" +
	"\x0eCHAIN_ID_AZTEC\x108\x12\x14\n" +
	"\x10CHAIN_ID_XRPLEVM\x109\x12\x13\n" +
	"\x0fCHAIN_ID_PLASMA\x10:\x12\x17\n" +
	"\x13CHAIN_ID_CREDITCOIN\x10;\x12\x13\n" +
	"\x0fCHAIN_ID_STACKS\x10<\x12\x10\n" +
	"\fCHAIN_ID_TON\x10=\x12\x17\n" +
	"\x12CHAIN_ID_WORMCHAIN\x10\xa0\x18\x12\x17\n" +
	"\x12CHAIN_ID_COSMOSHUB\x10\xa0\x1f\x12\x13\n" +
	"\x0eCHAIN_ID_EVMOS\x10\xa1\x1f\x12\x14\n" +
	"\x0fCHAIN_ID_KUJIRA\x10\xa2\x1f\x12\x15\n" +
	"\x10CHAIN_ID_NEUTRON\x10\xa3\x1f\x12\x16\n" +
	"\x11CHAIN_ID_CELESTIA\x10\xa4\x1f\x12\x16\n" +
	"\x11CHAIN_ID_STARGAZE\x10\xa5\x1f\x12\x12\n" +
	"\rCHAIN_ID_SEDA\x10\xa6\x1f\x12\x17\n" +
	"\x12CHAIN_ID_DYMENSION\x10\xa7\x1f\x12\x18\n" +
	"\x13CHAIN_ID_PROVENANCE\x10\xa8\x1f\x12\x13\n" +
	"\x0eCHAIN_ID_NOBLE\x10\xa9\x1f\x12\x15\n" +
	"\x10CHAIN_ID_SEPOLIA\x10\x92N\x12\x1e\n" +
	"\x19CHAIN_ID_ARBITRUM_SEPOLIA\x10\x93N\x12\x1a\n" +
	"\x15CHAIN_ID_BASE_SEPOLIA\x10\x94N\x12\x1e\n" +
	"\x19CHAIN_ID_OPTIMISM_SEPOLIA\x10\x95N\x12\x15\n" +
	"\x10CHAIN_ID_HOLESKY\x10\x96N\x12\x1d\n" +
	"\x18CHAIN_ID_POLYGON_SEPOLIA\x10\x97N2\xc6\t\n" +
	"\x10PublicRPCService\x12|\n" +
	"\x11GetLastHeartbeats\x12&.publicrpc.v1.GetLastHeartbeatsRequest\x1a'.publicrpc.v1.GetLastHeartbeatsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/heartbeats\x12\xbb\x01\n" +
	"\fGetSignedVAA\x12!.publicrpc.v1.GetSignedVAARequest\x1a\".publicrpc.v1.GetSignedVAAResponse\"d\x82\xd3\xe4\x93\x02^\x12\\/v1/signed_vaa/{message_id.emitter_chain}/{message_id.emitter_address}/{message_id.sequence}\x12\x91\x01\n" +
	"\x15GetCurrentGuardianSet\x12*.publicrpc.v1.GetCurrentGuardianSetRequest\x1a+.publicrpc.v1.GetCurrentGuardianSetResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/guardianset/current\x12\xcc\x01\n" +
	"#GovernorGetAvailableNotionalByChain\x128.publicrpc.v1.GovernorGetAvailableNotionalByChainRequest\x1a9.publicrpc.v1.GovernorGetAvailableNotionalByChainResponse\"0\x82\xd3\xe4\x93\x02*\x12(/v1/governor/available_notional_by_chain\x12\x9a\x01\n" +
	"\x17GovernorGetEnqueuedVAAs\x12,.publicrpc.v1.GovernorGetEnqueuedVAAsRequest\x1a-.publicrpc.v1.GovernorGetEnqueuedVAAsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/governor/enqueued_vaas\x12\xe4\x01\n" +
	"\x15GovernorIsVAAEnqueued\x12*.publicrpc.v1.GovernorIsVAAEnqueuedRequest\x1a+.publicrpc.v1.GovernorIsVAAEnqueuedResponse\"r\x82\xd3\xe4\x93\x02l\x12j/v1/governor/is_vaa_enqueued/{message_id.emitter_chain}/{message_id.emitter_address}/{message_id.sequence}\x12\x8e\x01\n" +
	"\x14GovernorGetTokenList\x12).publicrpc.v1.GovernorGetTokenListRequest\x1a*.publicrpc.v1.GovernorGetTokenListResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/governor/token_listBGZEgithub.com/certusone/wormhole/node/pkg/proto/publicrpc/v1;publicrpcv1b\x06proto3"

var (
	file_publicrpc_v1_publicrpc_proto_rawDescOnce sync.Once
	file_publicrpc_v1_publicrpc_proto_rawDescData []byte
)

func file_publicrpc_v1_publicrpc_proto_rawDescGZIP() []byte {
	file_publicrpc_v1_publicrpc_proto_rawDescOnce.Do(func() {
		file_publicrpc_v1_publicrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_publicrpc_v1_publicrpc_proto_rawDesc), len(file_publicrpc_v1_publicrpc_proto_rawDesc)))
	})
	return file_publicrpc_v1_publicrpc_proto_rawDescData
}

var file_publicrpc_v1_publicrpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_publicrpc_v1_publicrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_publicrpc_v1_publicrpc_proto_goTypes = []any{
	(ChainID)(0),                                              // 0: publicrpc.v1.ChainID
	(*MessageID)(nil),                                         // 1: publicrpc.v1.MessageID
	(*GetSignedVAARequest)(nil),                               // 2: publicrpc.v1.GetSignedVAARequest
	(*GetSignedVAAResponse)(nil),                              // 3: publicrpc.v1.GetSignedVAAResponse
	(*GetLastHeartbeatsRequest)(nil),                          // 4: publicrpc.v1.GetLastHeartbeatsRequest
	(*GetLastHeartbeatsResponse)(nil),                         // 5: publicrpc.v1.GetLastHeartbeatsResponse
	(*GetCurrentGuardianSetRequest)(nil),                      // 6: publicrpc.v1.GetCurrentGuardianSetRequest
	(*GetCurrentGuardianSetResponse)(nil),                     // 7: publicrpc.v1.GetCurrentGuardianSetResponse
	(*GuardianSet)(nil),                                       // 8: publicrpc.v1.GuardianSet
	(*GovernorGetAvailableNotionalByChainRequest)(nil),        // 9: publicrpc.v1.GovernorGetAvailableNotionalByChainRequest
	(*GovernorGetAvailableNotionalByChainResponse)(nil),       // 10: publicrpc.v1.GovernorGetAvailableNotionalByChainResponse
	(*GovernorGetEnqueuedVAAsRequest)(nil),                    // 11: publicrpc.v1.GovernorGetEnqueuedVAAsRequest
	(*GovernorGetEnqueuedVAAsResponse)(nil),                   // 12: publicrpc.v1.GovernorGetEnqueuedVAAsResponse
	(*GovernorIsVAAEnqueuedRequest)(nil),                      // 13: publicrpc.v1.GovernorIsVAAEnqueuedRequest
	(*GovernorIsVAAEnqueuedResponse)(nil),                     // 14: publicrpc.v1.GovernorIsVAAEnqueuedResponse
	(*GovernorGetTokenListRequest)(nil),                       // 15: publicrpc.v1.GovernorGetTokenListRequest
	(*GovernorGetTokenListResponse)(nil),                      // 16: publicrpc.v1.GovernorGetTokenListResponse
	(*GetLastHeartbeatsResponse_Entry)(nil),                   // 17: publicrpc.v1.GetLastHeartbeatsResponse.Entry
	(*GovernorGetAvailableNotionalByChainResponse_Entry)(nil), // 18: publicrpc.v1.GovernorGetAvailableNotionalByChainResponse.Entry
	(*GovernorGetEnqueuedVAAsResponse_Entry)(nil),             // 19: publicrpc.v1.GovernorGetEnqueuedVAAsResponse.Entry
	(*GovernorGetTokenListResponse_Entry)(nil),                // 20: publicrpc.v1.GovernorGetTokenListResponse.Entry
	(*v1.Heartbeat)(nil),                                      // 21: gossip.v1.Heartbeat
}
var file_publicrpc_v1_publicrpc_proto_depIdxs = []int32{
	0,  // 0: publicrpc.v1.MessageID.emitter_chain:type_name -> publicrpc.v1.ChainID
	1,  // 1: publicrpc.v1.GetSignedVAARequest.message_id:type_name -> publicrpc.v1.MessageID
	17, // 2: publicrpc.v1.GetLastHeartbeatsResponse.entries:type_name -> publicrpc.v1.GetLastHeartbeatsResponse.Entry
	8,  // 3: publicrpc.v1.GetCurrentGuardianSetResponse.guardian_set:type_name -> publicrpc.v1.GuardianSet
	18, // 4: publicrpc.v1.GovernorGetAvailableNotionalByChainResponse.entries:type_name -> publicrpc.v1.GovernorGetAvailableNotionalByChainResponse.Entry
	19, // 5: publicrpc.v1.GovernorGetEnqueuedVAAsResponse.entries:type_name -> publicrpc.v1.GovernorGetEnqueuedVAAsResponse.Entry
	1,  // 6: publicrpc.v1.GovernorIsVAAEnqueuedRequest.message_id:type_name -> publicrpc.v1.MessageID
	20, // 7: publicrpc.v1.GovernorGetTokenListResponse.entries:type_name -> publicrpc.v1.GovernorGetTokenListResponse.Entry
	21, // 8: publicrpc.v1.GetLastHeartbeatsResponse.Entry.raw_heartbeat:type_name -> gossip.v1.Heartbeat
	4,  // 9: publicrpc.v1.PublicRPCService.GetLastHeartbeats:input_type -> publicrpc.v1.GetLastHeartbeatsRequest
	2,  // 10: publicrpc.v1.PublicRPCService.GetSignedVAA:input_type -> publicrpc.v1.GetSignedVAARequest
	6,  // 11: publicrpc.v1.PublicRPCService.GetCurrentGuardianSet:input_type -> publicrpc.v1.GetCurrentGuardianSetRequest
	9,  // 12: publicrpc.v1.PublicRPCService.GovernorGetAvailableNotionalByChain:input_type -> publicrpc.v1.GovernorGetAvailableNotionalByChainRequest
	11, // 13: publicrpc.v1.PublicRPCService.GovernorGetEnqueuedVAAs:input_type -> publicrpc.v1.GovernorGetEnqueuedVAAsRequest
	13, // 14: publicrpc.v1.PublicRPCService.GovernorIsVAAEnqueued:input_type -> publicrpc.v1.GovernorIsVAAEnqueuedRequest
	15, // 15: publicrpc.v1.PublicRPCService.GovernorGetTokenList:input_type -> publicrpc.v1.GovernorGetTokenListRequest
	5,  // 16: publicrpc.v1.PublicRPCService.GetLastHeartbeats:output_type -> publicrpc.v1.GetLastHeartbeatsResponse
	3,  // 17: publicrpc.v1.PublicRPCService.GetSignedVAA:output_type -> publicrpc.v1.GetSignedVAAResponse
	7,  // 18: publicrpc.v1.PublicRPCService.GetCurrentGuardianSet:output_type -> publicrpc.v1.GetCurrentGuardianSetResponse
	10, // 19: publicrpc.v1.PublicRPCService.GovernorGetAvailableNotionalByChain:output_type -> publicrpc.v1.GovernorGetAvailableNotionalByChainResponse
	12, // 20: publicrpc.v1.PublicRPCService.GovernorGetEnqueuedVAAs:output_type -> publicrpc.v1.GovernorGetEnqueuedVAAsResponse
	14, // 21: publicrpc.v1.PublicRPCService.GovernorIsVAAEnqueued:output_type -> publicrpc.v1.GovernorIsVAAEnqueuedResponse
	16, // 22: publicrpc.v1.PublicRPCService.GovernorGetTokenList:output_type -> publicrpc.v1.GovernorGetTokenListResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_publicrpc_v1_publicrpc_proto_init() }
func file_publicrpc_v1_publicrpc_proto_init() {
	if File_publicrpc_v1_publicrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_publicrpc_v1_publicrpc_proto_rawDesc), len(file_publicrpc_v1_publicrpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_publicrpc_v1_publicrpc_proto_goTypes,
		DependencyIndexes: file_publicrpc_v1_publicrpc_proto_depIdxs,
		EnumInfos:         file_publicrpc_v1_publicrpc_proto_enumTypes,
		MessageInfos:      file_publicrpc_v1_publicrpc_proto_msgTypes,
	}.Build()
	File_publicrpc_v1_publicrpc_proto = out.File
	file_publicrpc_v1_publicrpc_proto_goTypes = nil
	file_publicrpc_v1_publicrpc_proto_depIdxs = nil
}
